# Generated by Django 4.2.25 on 2025-10-20 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('bilgisayar_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('ogretmen_no', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ogrenci_email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('rezervasyon_id', models.AutoField(primary_key=True, serialize=False)),
                ('tarih', models.DateField()),
                ('baslangic_saati', models.TimeField()),
                ('bitis_saati', models.TimeField()),
                ('durum', models.CharField(choices=[('Beklemede', 'Pending'), ('Onaylandı', 'Approved'), ('Reddedildi', 'Rejected')], default='Beklemede', max_length=50)),
                ('bilgisayar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.computer')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.student')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_adi', models.CharField(max_length=150)),
                ('kapasite', models.IntegerField()),
                ('sorumlu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.laboratory'),
        ),
    ]
