# Generated by Django 4.2.25 on 2025-10-25 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='sorumlu',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_labs', to=settings.AUTH_USER_MODEL),
        ),
    ]
