# Generated by Django 4.2.25 on 2025-10-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_laboratory_sorumlu_laboratory_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='ogrenci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.student'),
        ),
    ]
