# Generated by Django 4.2.25 on 2025-10-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_ogrenci'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='computer_name',
            field=models.CharField(default='Default_PC', max_length=100),
            preserve_default=False,
        ),
    ]
