# Generated by Django 4.2.25 on 2025-10-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_computer_computer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='operating_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='operating_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
