# Generated by Django 4.2.25 on 2025-11-03 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_laboratory_operating_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='ogrenci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.student'),
        ),
    ]
